//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngeliqueFinalProjecct
{
    using System;
    using System.Collections.Generic;
    
    public partial class FailedGDP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FailedGDP()
        {
            this.CommercialBanks = new HashSet<CommercialBank>();
            this.CommercialFinances = new HashSet<CommercialFinance>();
        }
    
        public double FBGDP_Id { get; set; }
        public Nullable<double> FK_FB_Id { get; set; }
        public Nullable<double> GDPPerCapita { get; set; }
        public Nullable<double> GDPGrowthPerCapitaQuarterToQuarter { get; set; }
        public Nullable<double> GDPInBillions { get; set; }
        public Nullable<double> GDPGrowthQuarterToQuarter { get; set; }
        public string ClosingDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialBank> CommercialBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialFinance> CommercialFinances { get; set; }
        public virtual FailedBank FailedBank { get; set; }
    }
}
