//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngeliqueFinalProjecct
{
    using System;
    using System.Collections.Generic;
    
    public partial class FailedBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FailedBank()
        {
            this.CommercialBanks = new HashSet<CommercialBank>();
            this.CommercialFinances = new HashSet<CommercialFinance>();
            this.FailedFinances = new HashSet<FailedFinance>();
            this.FailedGDPs = new HashSet<FailedGDP>();
        }
    
        public double FB_Id { get; set; }
        public Nullable<double> CERT { get; set; }
        public string ReportingDate { get; set; }
        public string BankName { get; set; }
        public string CITY { get; set; }
        public string COUNTY { get; set; }
        public string STATE { get; set; }
        public Nullable<double> TotalOffices { get; set; }
        public Nullable<double> TotalEmployees { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialBank> CommercialBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialFinance> CommercialFinances { get; set; }
        public virtual InstitutAll InstitutAll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FailedFinance> FailedFinances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FailedGDP> FailedGDPs { get; set; }
    }
}
