//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngeliqueFinalProjecct
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutesFinance
    {
        public string INSTFI_Id { get; set; }
        public Nullable<double> FK_CERT { get; set; }
        public Nullable<double> FK_CM_Id { get; set; }
        public Nullable<double> TotalOffices { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<double> TotalAssets { get; set; }
        public Nullable<double> DepartmentID { get; set; }
        public Nullable<double> TotalEquity { get; set; }
    
        public virtual CommercialBank CommercialBank { get; set; }
        public virtual CommercialFinance CommercialFinance { get; set; }
        public virtual InstitutAll InstitutAll { get; set; }
    }
}
