//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngeliqueFinalProjecct
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutesInsur
    {
        public string INSTIN_Id { get; set; }
        public Nullable<double> FK_CERT { get; set; }
        public Nullable<double> FK_CM_Id { get; set; }
        public Nullable<double> ROA { get; set; }
        public Nullable<double> ROAQ { get; set; }
        public Nullable<double> ROE { get; set; }
        public Nullable<double> ROEQ { get; set; }
        public Nullable<double> ROAPTX { get; set; }
        public Nullable<double> ROAPTXQ { get; set; }
        public Nullable<double> BankNetInc { get; set; }
        public string InsuranceFund { get; set; }
    
        public virtual CommercialBank CommercialBank { get; set; }
        public virtual CommercialFinance CommercialFinance { get; set; }
        public virtual InstitutAll InstitutAll { get; set; }
    }
}
