//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngeliqueFinalProjecct
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanksEntities : DbContext
    {
        public BanksEntities()
            : base("name=BanksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommercialBank> CommercialBanks { get; set; }
        public virtual DbSet<CommercialFinance> CommercialFinances { get; set; }
        public virtual DbSet<FailedBank> FailedBanks { get; set; }
        public virtual DbSet<FailedFinance> FailedFinances { get; set; }
        public virtual DbSet<FailedGDP> FailedGDPs { get; set; }
        public virtual DbSet<InstitutAll> InstitutAlls { get; set; }
        public virtual DbSet<InstitutesFinance> InstitutesFinances { get; set; }
        public virtual DbSet<InstitutesInsur> InstitutesInsurs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
