//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoUploadData
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NodeOrdersEntities : DbContext
    {
        public NodeOrdersEntities()
            : base("name=NodeOrdersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Order>().Ignore(t => t.StoreTable);
            modelBuilder.Entity<Order>().Ignore(t => t.CDTable);
            modelBuilder.Entity<Order>().Ignore(t => t.SalesPersonTable);
            //base.OnModelCreating(modelBuilder);
           // throw new UnintentionalCodeFirstException();
        }
        [NotMapped]
        public virtual DbSet<CDTable> CDTables { get; set; }
        [NotMapped]
        public virtual DbSet<Inventory> Inventories { get; set; }
        [NotMapped]
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        [NotMapped]
        public virtual DbSet<SalesPersonTable> SalesPersonTables { get; set; }
        [NotMapped]
        public virtual DbSet<StoreTable> StoreTables { get; set; }
    }
}
